name: semantic_tagger
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - alembic=1.10.3
  - alsa-lib=1.2.8
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=8.0.0
  - asttokens=2.2.1
  - async_generator=1.10
  - attr=2.5.1
  - attrs=22.2.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - blinker=1.6
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.22.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - catalogue=2.0.10
  - certifi=2022.12.7
  - certipy=0.1.3
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.2.0
  - cryptography=39.0.0
  - cycler=0.12.1
  - cymem=2.0.8
  - cython-blis=0.7.10
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.45.0
  - freetype=2.12.1
  - gettext=0.21.1
  - gflags=2.2.2
  - glib=2.78.1
  - glib-tools=2.78.1
  - glog=0.6.0
  - graphite2=1.3.13
  - greenlet=2.0.2
  - grpc-cpp=1.45.2
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.34
  - harfbuzz=6.0.0
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.2.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.2.0
  - importlib_resources=5.12.0
  - ipykernel=6.22.0
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - jack=1.9.22
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter-offlinenotebook=0.2.2
  - jupyter-resource-usage=0.7.0
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyter_server=1.23.6
  - jupyter_telemetry=0.1.0
  - jupyterhub-base=3.1.1
  - jupyterhub-singleuser=3.1.1
  - jupyterlab=3.4.8
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.7
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.2
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libgomp=12.2.0
  - libgoogle-cloud=1.40.2
  - libgpg-error=1.47
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.25
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libprotobuf=3.20.3
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libthrift=0.16.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - mako=1.2.4
  - markupsafe=2.1.2
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mpg123=1.32.3
  - munkres=1.1.4
  - murmurhash=1.0.10
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclassic=0.5.5
  - nbclient=0.7.3
  - nbconvert=7.3.0
  - nbconvert-core=7.3.0
  - nbconvert-pandoc=7.3.0
  - nbformat=5.8.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nltk=3.7
  - nodejs=18.12.1
  - notebook=6.4.12
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89
  - numpy=1.26.0
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openpyxl=3.0.9
  - openssl=1.1.1w
  - orc=1.7.5
  - packaging=23.0
  - pamela=1.0.0
  - pandas=1.4.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - pathy=0.10.2
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.3.1
  - pixman=0.42.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.2.0
  - ply=3.11
  - preshed=3.0.9
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pyarrow=8.0.0
  - pycparser=2.21
  - pydantic=1.8.2
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pyopenssl=23.1.1
  - pyparsing=3.1.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytz=2023.3
  - pyzmq=25.0.2
  - qt-main=5.15.6
  - re2=2022.06.01
  - readline=8.2
  - regex=2023.10.3
  - requests=2.28.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - s2n=1.0.10
  - send2trash=1.8.0
  - setuptools=67.6.1
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - spacy=3.3.1
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - spacy-model-en_core_web_sm=3.3.0
  - sqlalchemy=2.0.9
  - sqlite=3.40.0
  - srsly=2.4.8
  - stack_data=0.6.2
  - terminado=0.17.1
  - thinc=8.0.17
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.66.1
  - traitlets=5.9.0
  - typer=0.4.2
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - unicodedata2=15.1.0
  - urllib3=1.26.15
  - wasabi=0.10.1
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - click==8.0.4
      - pyexcelerate==0.10.0
      - pymusas==0.3.0
      # Chinese
      - https://github.com/explosion/spacy-models/releases/download/zh_core_web_sm-3.2.0/zh_core_web_sm-3.2.0-py3-none-any.whl
      - https://github.com/UCREL/pymusas-models/releases/download/cmn_dual_upos2usas_contextual-0.3.0/cmn_dual_upos2usas_contextual-0.3.0-py3-none-any.whl
      - https://github.com/UCREL/pymusas-models/releases/download/cmn_single_upos2usas_contextual-0.3.1/cmn_single_upos2usas_contextual-0.3.1-py3-none-any.whl
      # italian
      - https://github.com/explosion/spacy-models/releases/download/it_core_news_sm-3.2.0/it_core_news_sm-3.2.0-py3-none-any.whl
      - https://github.com/UCREL/pymusas-models/releases/download/it_dual_upos2usas_contextual-0.3.0/it_dual_upos2usas_contextual-0.3.0-py3-none-any.whl
      - https://github.com/UCREL/pymusas-models/releases/download/it_single_upos2usas_contextual-0.3.1/it_single_upos2usas_contextual-0.3.1-py3-none-any.whl
      # spanish
      - https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.2.0/es_core_news_sm-3.2.0-py3-none-any.whl
      - https://github.com/UCREL/pymusas-models/releases/download/es_dual_upos2usas_contextual-0.3.0/es_dual_upos2usas_contextual-0.3.0-py3-none-any.whl
      - https://github.com/UCREL/pymusas-models/releases/download/es_single_upos2usas_contextual-0.3.1/es_single_upos2usas_contextual-0.3.1-py3-none-any.whl