#!/usr/bin/env python3
name: semantic_tagger

channels:
  - conda-forge
  - defaults
  
dependencies:
  # try to install everything via conda where possible,
  # makes for simpler and quicker installs
  - jupyterlab=3.3.3
  - python=3.8.13
  - spacy=3.3.1
  - spacy-model-en_core_web_sm=3.3.0
  - pandas=1.4.3
  - openpyxl=3.0.9
  - nltk=3.7
  - ipywidgets=7.6.5
  - pyarrow==8.0.0
  - matplotlib
  - pip
  - pip:
      - langdetect
      - pyexcelerate
      - https://github.com/UCREL/pymusas-models/releases/download/en_single_none_contextual-0.3.1/en_single_none_contextual-0.3.1-py3-none-any.whl
      - https://github.com/UCREL/pymusas-models/releases/download/en_dual_none_contextual-0.3.1/en_dual_none_contextual-0.3.1-py3-none-any.whl