#!/usr/bin/env python3
name: semantic_tagger

channels:
  - conda-forge
  - defaults
  
dependencies:
  # try to install everything via conda where possible,
  # makes for simpler and quicker installs
  - python=3.9.12
  - spacy=3.3.1
  - pandas=1.4.3
  - openpyxl=3.0.9
  - nltk=3.7
  - ipywidgets=7.6.5
  - pyarrow==8.0.0
  - matplotlib
  - pip
  - pip:
      - pyexcelerate