#!/usr/bin/env python3
name: semantic_tagger

channels:
  - conda-forge
  - defaults
  
dependencies:
  # try to install everything via conda where possible,
  # makes for simpler and quicker installs
  - python=3.8.13
  - spacy=3.3.1
  - pandas=1.4.4
  - openpyxl=3.0.10
  - nltk=3.7
  - ipywidgets=7.6.5
  - matplotlib
  - pip
  - pip:
      - pyexcelerate